### ISSUE TITLE
Latest OneSignal breaks Yoast 10 in Admin area (posts, products)

### ISSUE THREAD

**Issue by mitchellkrogza** [OneSignal/OneSignal-WordPress-Plugin#177]
**Description:**
Latest plugin version completely breaks Yoast 10 in the admin interface, posts, pages, products all affected.

**Steps to Reproduce Issue:**

1. update to latest plugin 
2. write a post and see no Yoast meta boxes visible
3.

**Anything else:**

**Comment by altendorfme** [comment]
Console:
`notice.js?ver=1.1:26 Uncaught TypeError: Cannot read property 'getCurrentPost' of undefined
    at wp.data.subscribe (notice.js?ver=1.1:26)
    at data.min.js?ver=4.2.1:1
    at Array.forEach (<anonymous>)
    at n (data.min.js?ver=4.2.1:1)
    at data.min.js?ver=4.2.1:1
    at b (data.min.js?ver=4.2.1:1)
    at data.min.js?ver=4.2.1:1
    at Object.dispatch (data.min.js?ver=4.2.1:1)
    at wp-seo-post-scraper-1000.min.js?ver=10.0:1
    at analysis-1000.min.js?ver=10.0:10`

**Comment by firojghimire** [comment]
adding 'wp-editor' script handle in dependency array fixes the issue.

add wp-editor in onesignal-admin.php like this:

wp_register_script('notice_script', plugins_url('notice.js', __FILE__), array('jquery','wp-editor'), '1.1', true);

Hope they will fix the issue in next update!

**Comment by chroust** [comment]
@firojghimire your fix help me. Thanks

**Comment by rgomezp** [comment]
We have released v1.16.16. Please update and do a hard-refresh

**Comment by mitchellkrogza** [comment]
Seems ok now, thanks for the quick response guys :+1:  Will monitor to see if it crops up again.

**Comment by rgomezp** [comment]
@mitchellkrogza you can beta test the [next release](https://github.com/OneSignal/OneSignal-WordPress-Plugin/archive/1.17.0.zip) if you wish. 

Also, would really appreciate if you [left us a review](https://wordpress.org/support/plugin/onesignal-free-web-push-notifications/reviews/#new-post). Thanks!

**Comment by peterolle** [comment]
@chroust can you share that fix?

1.17.0 and the problem persist.

Can anyone share a fix for this?

**Comment by mitchellkrogza** [comment]
@peterolle did you ctrl+reload the admin area?

**Comment by peterolle** [comment]
@mitchellkrogza I just deleted and reinstalled the plugin and now its showing. Thank you!

**Comment by rgomezp** [comment]
@peterolle ,
Great to hear!
