### ISSUE TITLE
OneSignal.js HTTP responde code 403

### ISSUE THREAD

**Issue by dcarrero** [OneSignal/OneSignal-WordPress-Plugin#65]
I have this error and i don't know to solve:

A bad HTTP response code (403) was received when fetching the script.
https://navidad.es/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKWorker.js.php Failed to load resource: net::ERR_INVALID_RESPONSE
OneSignal.js:1290 ServiceWorker registration TypeError: Failed to register a ServiceWorker: A bad HTTP response code (403) was received when fetching the script.K @ OneSignal.js:1290

**Comment by jasonpang** [comment]
Hi @dcarrero,

Sorry I missed this.

Some of the files our WordPress plugin automatically includes in your page is not publicly accessible due to what appears to be your server's settings limiting access to these files:

```
site.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKWorker.js.php
site.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKUpdaterWorker.js.php
site.com/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/manifest.json.php
```

Can you please check for things that might be blocking these three specific files? The browser looks at these files when subscribing, so they need to be publicly accessible.

In the past, some users have been able to solve the issue by checking their .htaccess file settings.

**Comment by dcarrero** [comment]
Thanks, I review my .htaccess file and it's ok.

But I can't run in my site herencia.net

now the error is 

ServiceWorker registration TypeError: ServiceWorker script at https://herencia.net/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKWorker.js.php for scope https://herencia.net/ encountered an error during installation.

**Comment by jasonpang** [comment]
Hello @dcarrero,

We've fixed part of the issue, but it looks like you need to reset the subscription for your users. This process can take time, because it only takes effect for each user when they visit your website again.

To reset all of your user's subscriptions for your app, please follow these instructions:

Please install the WordPress plugin CSS & JavaScript Toolbox.
Please paste the following code for the textbox contents:

```js
<script>
window.OneSignal = window.OneSignal || [];
OneSignal.push(function() {
    OneSignal.once('initialize', function() {
        OneSignal.config.dangerouslyResetUserSubscriptions = 'reset-1';
        OneSignal.checkAndWipeUserSubscription();
    });
});
</script>
​```

It should look like this: http://i.imgur.com/JiyQtqx.png. Be sure to click "Save Changes" after you've pasted the code.

That's all! 

This reset only takes affect for the user when they visit the page. The user must visit the page with this code at least once before their subscription is reset.

A user visiting the same page multiple times will have no effect once they have already been reset once.

Also, please don't change the "reset-1" string to any other value or it will reset everyone's subscriptions again.

**Comment by jasonpang** [comment]
Looks like this is solved.

**Comment by jasonpang** [comment]
Another user that solved this had this to say:

```
It was a similar plugin, Defender by WPMUDev which does the same thing by preventing PHP execution. But I added exceptions to the .htaccess file for each of those filenames and it all works now while still protecting everything else.

In case you’re interested, or want to document it or it can help other WordPress customers, here’s the .htaccess file in my /wp-content folder:

## WP Defender - Protect PHP Executed ##

<Files *.php>

Order allow,deny

Deny from all

</Files>

<Files OneSignalSDKWorker.js.php>

Allow from all

</Files>

<Files OneSignalSDKUpdaterWorker.js.php>

Allow from all

</Files>

<Files manifest.json.php>

Allow from all

</Files>

## WP Defender - End ##

That works :)
```

**Comment by kolbear** [comment]
The examples above may cause an error (403 for example)
You can add this exclude code in .htaccess : 
`RewriteEngine On
RewriteCond %{REQUEST_URI} ^/wp-content/plugins/onesignal-free-web-push-notifications
RewriteRule (.*) $1 [L]`

Works great, test it at site [https://go-to.rest/](url)

**Comment by Gaurang033** [comment]
@kolbear 
I am getting the same error for my wordpress blog. As suggested I added two lines to my `.htaccess` file however, I am still getting error. 

**.htaccess**

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On RewriteCond %{REQUEST_URI} ^/wp-content/plugins/onesignal-free-web-push-notifications
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]

RewriteRule (.*) $1 [L]
</IfModule>

# END WordPress
```

**Comment by jkasten2** [comment]
@Gaurang033 I visited your site however it seems the OneSignal plugin is not enabled as I don't see any OneSignal related entires at all in page source. Can you make sure it has been enabled from wp admin after it was installed? I also recommend checking if there any PHP errors in your logs if you have enabled it

**Comment by jkasten2** [comment]
@Gaurang033 What version of Wordpress and PHP are you using?

Do you have any other Wordpress plugins or caching that could be making the admin page return a 403 by blocking access?

**Comment by Gaurang033** [comment]
I have multiple plugins installed, for cache it's **wp fastest cache**. I disabled all the plugin and tried to enable OneSignal, however it still showed the same error.

**Comment by phaser32** [comment]
Good evening to everyone, I finally solved the issue in the following way:
- Go to onesignal dasboard
- Select Your project > setting and choose custom code
- Flag "My site is not fully HTTPS" (also if You got)
- Choose a label (eg. mywebsite)
- Go to wordpress backend and deselect "My site uses an HTTPS connection (SSL)" (if You got)
- Fill in the OneSignal Label field Your label (eg. mywebsite.os.tc)
Try it and everything works like a charm!
I hope could be helpful for someone.
What's happen? I suppose that Onesignal doesn't work correctly if You have an SLL open source (like Let's encrypt). I suppose it need an extended certificate (like wildcard and so on).
This is just a guess.
Peace out
Ale
